services:
  - type: web
    name: garud-kavach-server
    runtime: go
    repo: https://github.com/ayushsingh-22/Garud-Kavach-Server
    branch: master
    buildCommand: go build -o server .
    startCommand: ./server
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: GUARD_FRONTEND_URL
        value: https://garud-kavach-guard.vercel.app
      - key: REDIS_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_API_KEY_2
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: EMAILJS_SERVICE_ID
        sync: false
      - key: EMAILJS_TEMPLATE_ID
        sync: false
      - key: EMAILJS_PUBLIC_KEY
        sync: false
      - key: EMAILJS_PRIVATE_KEY
        sync: false
      - key: ADMIN_SECURITY_CODE
        sync: false
